LinkedOutInc/linkedout

- backend/pom.xml
- backend/src/main/java/app/linkedout/BackendApplication.java
- backend/src/test/java/app/linkedout/BackendApplicationTests.java
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/linkedout353/linkedout/pull/7).
* __->__ #7
backend init 2
> backend init 2

- backend/src/main/java/app/linkedout/bootstrap/BackendBootstrap.java
> [API] BackendBootstrap.java added for testing purposes

- www/package-lock.json
- www/package.json
- www/src/index.css
- www/tailwind.config.js
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/linkedout353/linkedout/pull/18).
* #20
* #19
* __->__ #18
[UI] init tailwind
> [UI] init tailwind

- www/package-lock.json
- www/package.json
- www/public/index.html
- www/src/App.js
- www/src/index.js
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/22).
* #24
* __->__ #22
* #25
[UI] Small Branding Changes
> [UI] Small Branding Changes

- www/package-lock.json
- www/package.json
- www/src/App.js
- www/src/index.js
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/25).
* #24
* #22
* __->__ #25
[UI] Routing
> [UI] Routing

- www/package-lock.json
- www/package.json
- www/public/index.html
- www/src/App.js
- www/src/components/common/footer/index.jsx
- www/src/components/common/header/index.jsx
- www/src/components/common/logo/index.jsx
- www/src/components/index.jsx
- www/src/components/pages/landing/hero/index.jsx
- www/src/components/pages/login/index.jsx
- www/src/index.js
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/24).
* __->__ #24
* #22
* #25
[UI] Login + Various Responsiveness Fixes
Added sign in page + various responsiveness improvements.
Sign in page accessible via /login or navigation button
> [UI] Login + Various Responsiveness Fixes

- www/src/components/pages/login/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/27).
* #28
* __->__ #27
[UI] Login input forms changed
Looks better now
> [UI] Login input forms changed

- www/src/App.js
- www/src/components/common/header/index.jsx
- www/src/components/index.jsx
- www/src/components/pages/landing/hero/index.jsx
- www/src/components/pages/login/index.jsx
- www/src/components/pages/signup/Complete.jsx
- www/src/components/pages/signup/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/28).
* __->__ #28
* #27
[UI] Signup
> [UI] Signup

- www/src/components/index.jsx
- www/src/components/pages/signup/complete/index.jsx
- www/src/components/pages/signup/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/30).
* #31
* __->__ #30
[UI] Responsiveness fixes
> [UI] Responsiveness fixes

- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/signup/complete/index.jsx
- www/src/components/pages/signup/createProfile/index.jsx
- www/src/components/pages/signup/index.jsx
- www/src/components/pages/signup/profileCreation/index.jsx
- www/src/components/pages/signup/profilePicture/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/31).
* __->__ #31
* #30
[UI] Profile Info
> [UI] Profile Info

- .vscode/settings.json
- backend/bin/target/classes/application.properties
- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/feed/index.jsx
- www/src/components/pages/feed/newPost/index.jsx
- www/src/components/pages/feed/post/index.jsx
> [UI] Feed posts

- .gitignore
- .vscode/settings.json
- www/src/components/pages/feed/index.jsx
- www/src/components/pages/feed/newPost/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/47).
* __->__ #47
* #40
.gitignore for .vscode
> .gitignore for .vscode

- .gitignore
- backend/.gitignore
- backend/bin/target/classes/application.properties
- www/src/App.css
- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/jobs/JobDescription/index.jsx
- www/src/components/pages/jobs/JobItem/index.jsx
- www/src/components/pages/jobs/JobSearch/index.jsx
- www/src/components/pages/jobs/index.jsx
- www/src/components/pages/notFound/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
- www/src/components/pages/profile/interests/index.jsx
- www/src/components/pages/profile/interests/interestItem/index.jsx
- www/src/index.css
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/56).
* __->__ #56
* #55
* #54
* #53
* #51
* #50
* #49
* #48
[UI] 404 Page added
/s for obvious reasons
> [UI] 404 Page added

- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/48).
* #56
* #55
* #54
* #53
* #51
* #50
* #49
* __->__ #48
[UI] Profile banner
> [UI] Profile banner

- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/49).
* #56
* #55
* #54
* #53
* #51
* #50
* __->__ #49
* #48
[UI] Profile experiences
> [UI] Profile experiences

- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/50).
* #56
* #55
* #54
* #53
* #51
* __->__ #50
* #49
* #48
[UI] Profile Education
> [UI] Profile Education

- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
- www/src/components/pages/profile/interests/index.jsx
- www/src/components/pages/profile/interests/interestItem/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/51).
* #56
* #55
* #54
* #53
* __->__ #51
* #50
* #49
* #48
[UI] Profile interests
Profile section is done. Available at /profile
> [UI] Profile interests

- .gitignore
- backend/.gitignore
- backend/bin/target/classes/application.properties
- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
- www/src/components/pages/profile/interests/index.jsx
- www/src/components/pages/profile/interests/interestItem/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/53).
* #56
* #55
* #54
* __->__ #53
* #51
* #50
* #49
* #48
[MISC] .gitignore
> [MISC] .gitignore

- .gitignore
- backend/.gitignore
- backend/bin/target/classes/application.properties
- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/jobs/JobDescription/index.jsx
- www/src/components/pages/jobs/JobItem/index.jsx
- www/src/components/pages/jobs/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
- www/src/components/pages/profile/interests/index.jsx
- www/src/components/pages/profile/interests/interestItem/index.jsx
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/54).
* #56
* #55
* __->__ #54
* #53
* #51
* #50
* #49
* #48
[UI] Job List + Description
UI for viewing list of jobs and selecting each one to view their description. Available at /jobs
> [UI] Job List + Description

- .gitignore
- backend/.gitignore
- backend/bin/target/classes/application.properties
- www/src/App.css
- www/src/App.js
- www/src/components/index.jsx
- www/src/components/pages/jobs/JobDescription/index.jsx
- www/src/components/pages/jobs/JobItem/index.jsx
- www/src/components/pages/jobs/JobSearch/index.jsx
- www/src/components/pages/jobs/index.jsx
- www/src/components/pages/profile/banner/index.jsx
- www/src/components/pages/profile/education/educationItem/index.jsx
- www/src/components/pages/profile/education/index.jsx
- www/src/components/pages/profile/experience/experienceItem/index.jsx
- www/src/components/pages/profile/experience/index.jsx
- www/src/components/pages/profile/index.jsx
- www/src/components/pages/profile/interests/index.jsx
- www/src/components/pages/profile/interests/interestItem/index.jsx
- www/src/index.css
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/55).
* #56
* __->__ #55
* #54
* #53
* #51
* #50
* #49
* #48
[UI] Job Search
Added job search + filter to /jobs/
Also changed global focus outline color to linkedout
> [UI] Job Search

- www/public/manifest.json
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/LinkedOutInc/linkedout/pull/61).
* __->__ #61
[MISC] manifest fix
> [MISC] manifest fix
